PROVIDERS_AND_MODELS = [
    ["openai", "gpt-4o-mini"],
    ["openai", "gpt-4o"],
    ["mistral", "mistral-small-latest"],
    ["mistral", "mistral-medium-latest"],
    ["mistral", "mistral-large-latest"],
]

NAMES = [
    "Lucas",
    "John",
    "Martin",
    "Emily",
    "Sarah",
    "David",
    "James",
    "Robert",
    "William",
    "Joseph",
]

SECRET_WORD = [
    "apple",
    "car",
    "France",
    "Neuroscience",
    "Generosity",
    "War",
    "Pillow",
    "bark",
    "crane",
    "spring",
    "pitch",
    "draft",
    "seal",
    "bank",
    "ring",
    "trunk",
    "organ",
    "mole",
    "bug",
    "file",
    "charge",
    "mint",
    "cell",
    "bond",
    "root",
    "scale",
    "volume",
    "vector",
    "channel",
    "medium",
    "model",
    "terminal",
    "kernel",
    "matrix",
    "orbit",
    "cache",
    "token",
    "circuit",
    "field",
    "phase",
    "flux",
    "note",
    "chord",
    "bluff",
    "staple",
    "mold",
    "delta",
]
